#!/usr/bin/env python3
import requests
from bs4 import BeautifulSoup
import json
import re
import time
import os
from datetime import datetime, timedelta
from config.settings import USER_AGENT, REQUEST_TIMEOUT, REQUEST_INTERVAL

# 可选数据源库
try:
    import baostock as bs
    HAS_BAOSTOCK = True
except ImportError:
    HAS_BAOSTOCK = False

try:
    import akshare as ak
    HAS_AKSHARE = True
except ImportError:
    HAS_AKSHARE = False

try:
    import finnhub
    FINNHUB_API_KEY = os.getenv('FINNHUB_API_KEY', '')
    HAS_FINNHUB = bool(FINNHUB_API_KEY)
except ImportError:
    HAS_FINNHUB = False
    FINNHUB_API_KEY = ''

# Twelve Data API (免费额度，需要注册获取API key)
TWELVEDATA_API_KEY = os.getenv('TWELVEDATA_API_KEY', '')
HAS_TWELVEDATA = bool(TWELVEDATA_API_KEY)

class DataFetcher:
    def __init__(self):
        self.headers = {'User-Agent': USER_AGENT}
        self.session = requests.Session()
        self.session.headers.update(self.headers)
        # 腾讯财经请求头
        self.qq_headers = {
            'User-Agent': USER_AGENT,
            'Referer': 'https://stockapp.finance.qq.com/'
        }

    def fetch_all_data(self, time_info):
        data = {}
        data['us_stock'] = self._fetch_us_stock(time_info)
        time.sleep(REQUEST_INTERVAL)
        data['commodity'] = self._fetch_commodity(time_info)
        time.sleep(REQUEST_INTERVAL)
        data['a_stock'] = self._fetch_a_stock(time_info)
        time.sleep(REQUEST_INTERVAL)
        data['sectors'] = self._fetch_sectors(time_info)
        time.sleep(REQUEST_INTERVAL)
        data['lhb'] = self._fetch_lhb(time_info)
        time.sleep(REQUEST_INTERVAL)
        data['northbound'] = self._fetch_northbound(time_info)
        data['news'] = self._fetch_news(time_info)
        return data

    def _safe_get(self, url, max_retries=2, **kwargs):
        for attempt in range(max_retries):
            try:
                resp = self.session.get(url, timeout=REQUEST_TIMEOUT, **kwargs)
                resp.encoding = resp.apparent_encoding or 'utf-8'
                return resp
            except Exception as e:
                if attempt < max_retries - 1:
                    time.sleep(1)
                    continue
                print(f'Request failed: {url[:60]}... - {e}')
                return None

    def _fetch_us_stock(self, time_info):
        result = {'djia':{}, 'nasdaq':{}, 'sp500':{}, 'summary':''}
        try:
            # 1. 优先尝试腾讯财经API
            if self._fetch_us_stock_qq(result):
                print('US stock: QQ Finance OK')
            # 2. 如果腾讯失败，尝试新浪财经
            elif self._fetch_us_stock_sina(result):
                print('US stock: Sina fallback OK')
            # 3. 如果新浪也失败，尝试Twelve Data
            elif HAS_TWELVEDATA and self._fetch_us_stock_twelvedata(result):
                print('US stock: Twelve Data fallback OK')
            # 4. 如果Twelve Data也失败，尝试finnhub
            elif HAS_FINNHUB and self._fetch_us_stock_finnhub(result):
                print('US stock: Finnhub fallback OK')

            # Summary will be generated by AI later
            result['summary'] = ''
        except Exception as e:
            print(f'US stock fetch error: {e}')
            self._fetch_us_stock_sina(result)
        return result

    def _fetch_us_stock_qq(self, result):
        """从腾讯财经获取美股数据"""
        try:
            url = 'https://qt.gtimg.cn/q=usDJI,usIXIC,usINX'
            resp = self._safe_get(url, headers=self.qq_headers)
            if resp and resp.status_code == 200:
                text = resp.text
                # 解析格式: v_usDJI="200~道琼斯~.DJI~50063.46~49693.20~...~370.26~0.75~..."
                for line in text.strip().split('\n'):
                    if 'v_usDJI=' in line:
                        parts = line.split('~')
                        if len(parts) >= 33:
                            result['djia'] = {'point': parts[3], 'pct': parts[32], 'note': ''}
                    elif 'v_usIXIC=' in line:
                        parts = line.split('~')
                        if len(parts) >= 33:
                            result['nasdaq'] = {'point': parts[3], 'pct': parts[32], 'note': ''}
                    elif 'v_usINX=' in line:
                        parts = line.split('~')
                        if len(parts) >= 33:
                            result['sp500'] = {'point': parts[3], 'pct': parts[32], 'note': ''}
                return any(result[k].get('point') for k in ['djia', 'nasdaq', 'sp500'])
        except Exception as e:
            print(f'QQ US stock error: {e}')
        return False
    
    def _fetch_us_stock_sina(self, result):
        """Fetch US stock data from Sina Finance - fallback"""
        try:
            headers = {
                'User-Agent': USER_AGENT,
                'Referer': 'https://finance.sina.com.cn/'
            }
            # 新浪财经美股代码：道琼斯=gb_dji, 纳斯达克=gb_ixic, 标普500=gb_inx
            url = 'https://hq.sinajs.cn/list=gb_dji,gb_ixic,gb_inx'
            resp = self._safe_get(url, headers=headers)
            
            if resp:
                text = resp.text
                lines = text.strip().split('\n')
                for line in lines:
                    line = line.strip()
                    # 解析道琼斯
                    if line.startswith('var hq_str_gb_dji'):
                        # 格式: var hq_str_gb_dji="道琼斯,49693.1992,-0.14,2026-05-14 04:55:44,...
                        parts = line.split('="')[1].rstrip('";').split(',')
                        if len(parts) >= 3:
                            result['djia'] = {
                                'point': parts[1],  # 点位
                                'pct': parts[2],    # 涨跌幅
                                'note': ''
                            }
                    # 解析纳斯达克
                    elif line.startswith('var hq_str_gb_ixic'):
                        parts = line.split('="')[1].rstrip('";').split(',')
                        if len(parts) >= 3:
                            result['nasdaq'] = {
                                'point': parts[1],
                                'pct': parts[2],
                                'note': ''
                            }
                    # 解析标普500
                    elif line.startswith('var hq_str_gb_inx'):
                        parts = line.split('="')[1].rstrip('";').split(',')
                        if len(parts) >= 3:
                            result['sp500'] = {
                                'point': parts[1],
                                'pct': parts[2],
                                'note': ''
                            }
                print(f'Sina fallback success: DJIA={result["djia"].get("point",0)}, NASDAQ={result["nasdaq"].get("point",0)}, SPX={result["sp500"].get("point",0)}')
                return any(result[k].get('point') for k in ['djia', 'nasdaq', 'sp500'])
        except Exception as e:
            print(f'Sina US stock fallback error: {e}')
        return False

    def _fetch_us_stock_twelvedata(self, result):
        """使用Twelve Data获取美股数据"""
        try:
            # 美股指数代码
            indices = [
                ('djia', '^DJI'),
                ('nasdaq', '^IXIC'),
                ('sp500', '^GSPC')
            ]

            for key, symbol in indices:
                try:
                    url = 'https://api.twelvedata.com/time_series'
                    params = {
                        'symbol': symbol,
                        'interval': '1day',
                        'outputsize': '2',
                        'apikey': TWELVEDATA_API_KEY
                    }

                    resp = self._safe_get(url, params=params)
                    if resp:
                        data = resp.json()
                        if data.get('status') == 'ok' and data.get('values'):
                            values = data['values']
                            current = float(values[0]['close'])
                            prev = float(values[1]['close']) if len(values) > 1 else current
                            pct = round((current - prev) / prev * 100, 2) if prev > 0 else 0

                            result[key] = {
                                'point': str(current),
                                'pct': str(pct),
                                'note': ''
                            }
                            print(f'Twelve Data {key}: {current}, {pct}%')
                except Exception as e:
                    print(f'Twelve Data {key} error: {e}')

        except Exception as e:
            print(f'Twelve Data US stock error: {e}')

    def _fetch_us_stock_finnhub(self, result):
        """使用finnhub获取美股数据"""
        try:
            client = finnhub.Client(api_key=FINNHUB_API_KEY)

            # 美股指数代码
            indices = [
                ('djia', '^DJI'),
                ('nasdaq', '^IXIC'),
                ('sp500', '^GSPC')
            ]

            for key, symbol in indices:
                try:
                    quote = client.quote(symbol)
                    if quote and quote.get('c'):
                        current = quote['c']
                        prev_close = quote.get('pc', current)
                        pct = round((current - prev_close) / prev_close * 100, 2) if prev_close > 0 else 0

                        result[key] = {
                            'point': str(current),
                            'pct': str(pct),
                            'note': ''
                        }
                        print(f'Finnhub {key}: {current}, {pct}%')
                except Exception as e:
                    print(f'Finnhub {key} error: {e}')

        except Exception as e:
            print(f'Finnhub US stock error: {e}')

    def _fetch_commodity(self, time_info):
        result = {}

        # 1. 优先尝试腾讯财经API
        self._fetch_commodity_qq(result)

        # 2. 对于失败的商品，尝试新浪财经备用
        for key in ['gold', 'wti', 'brent']:
            if key not in result or result.get(key, {}).get('need_ai'):
                self._fetch_commodity_sina(result, key)

        # 3. 对于仍然失败的商品，尝试东方财富备用
        for key in ['gold', 'wti', 'brent']:
            if key not in result or result.get(key, {}).get('need_ai'):
                self._fetch_commodity_eastmoney_single(result, key)

        return result

    def _fetch_commodity_qq(self, result):
        """从腾讯财经获取商品数据"""
        try:
            url = 'https://qt.gtimg.cn/q=hf_GC,hf_CL,hf_OIL'
            resp = self._safe_get(url, headers=self.qq_headers)
            if resp and resp.status_code == 200:
                text = resp.text
                # 解析格式: v_hf_GC="4580.57,-2.24,4582.50,..."
                for line in text.strip().split('\n'):
                    if 'v_hf_GC=' in line:
                        data = line.split('"')[1] if '"' in line else ''
                        parts = data.split(',')
                        if len(parts) >= 2:
                            result['gold'] = {'price': parts[0], 'pct': parts[1]}
                    elif 'v_hf_CL=' in line:
                        data = line.split('"')[1] if '"' in line else ''
                        parts = data.split(',')
                        if len(parts) >= 2:
                            result['wti'] = {'price': parts[0], 'pct': parts[1]}
                    elif 'v_hf_OIL=' in line:
                        data = line.split('"')[1] if '"' in line else ''
                        parts = data.split(',')
                        if len(parts) >= 2:
                            result['brent'] = {'price': parts[0], 'pct': parts[1]}
                print(f'QQ commodity: gold={result.get("gold",{}).get("price")}, wti={result.get("wti",{}).get("price")}, brent={result.get("brent",{}).get("price")}')
        except Exception as e:
            print(f'QQ commodity error: {e}')
    
    def _fetch_commodity_eastmoney_single(self, result, commodity_type):
        """从东方财富获取单个商品数据（备用）"""
        try:
            secid_map = {
                'gold': '101.GC00Y',
                'wti': '101.CL00Y',
                'brent': '101.B00Y'
            }
            secid = secid_map.get(commodity_type)
            if not secid:
                return

            url = f'https://push2.eastmoney.com/api/qt/stock/get?secid={secid}&fields=f43,f170'
            resp = self._safe_get(url)
            if resp:
                resp_data = resp.json()
                d = resp_data.get('data') if resp_data else None
                if d and d.get('f43'):
                    # 黄金使用/10，原油使用/100
                    divisor = 10 if commodity_type == 'gold' else 100
                    result[commodity_type] = {'price': str(d.get('f43', 0) / divisor), 'pct': str(d.get('f170', 0) / 100)}
                    print(f'Eastmoney {commodity_type}: {result[commodity_type]["price"]}')
        except Exception as e:
            print(f'Eastmoney {commodity_type} error: {e}')
    
    def _fetch_commodity_sina(self, result, commodity_type):
        """从新浪财经获取商品数据（备用）"""
        try:
            # 新浪财经商品代码
            sina_codes = {
                'gold': 'hf_GC',  # 黄金
                'wti': 'hf_CL',   # WTI原油
                'brent': 'hf_OIL' # 布伦特原油
            }
            
            code = sina_codes.get(commodity_type)
            if not code:
                return
            
            url = f'https://hq.sinajs.cn/list={code}'
            headers = {
                'User-Agent': USER_AGENT,
                'Referer': 'https://finance.sina.com.cn/'
            }
            
            resp = self._safe_get(url, headers=headers)
            if resp and resp.status_code == 200:
                text = resp.text
                # 解析格式: var hq_str_xxx="价格,涨跌幅,..."
                if '="' in text:
                    parts = text.split('="')[1].rstrip('";').split(',')
                    if len(parts) >= 2:
                        try:
                            price = float(parts[0])
                            # 计算涨跌幅（如果有前一日收盘价）
                            pct = 0
                            if len(parts) > 7 and parts[7]:
                                prev_close = float(parts[7])
                                if prev_close > 0:
                                    pct = round((price - prev_close) / prev_close * 100, 2)
                            
                            result[commodity_type] = {'price': str(price), 'pct': str(pct)}
                            print(f'Sina {commodity_type} data: price={price}, pct={pct}%')
                        except Exception as e:
                            print(f'Sina {commodity_type} parse error: {e}')
        except Exception as e:
            print(f'Sina {commodity_type} error: {e}')

    def _fetch_a_stock(self, time_info):
        """获取A股市场数据，优先使用腾讯财经"""
        result = {'sh': {}, 'sz': {}, 'cy': {}, 'total_vol': 0}

        try:
            indices = [
                ('sh', 'sh000001', '上证指数', 'sh.000001'),
                ('sz', 'sz399001', '深证成指', 'sz.399001'),
                ('cy', 'sz399006', '创业板指', 'sz.399006')
            ]

            total_vol = 0

            # 1. 优先尝试腾讯财经API（批量获取）
            qq_success = self._fetch_a_stock_qq(result, indices, total_vol)
            if qq_success:
                total_vol = qq_success
                print(f'A stock using QQ Finance: total_vol={total_vol}亿')
            else:
                # 2. 如果腾讯失败，尝试逐个获取
                for key, secid, name, bs_code in indices:
                    # 尝试新浪财经
                    sina_data = self._fetch_a_stock_sina_single(key, name)
                    if sina_data:
                        result[key] = sina_data
                        if key in ('sh', 'sz'):
                            total_vol += float(sina_data.get('vol', 0))
                        print(f'{name} using sina: {sina_data["point"]}, {sina_data["pct"]}%')
                        continue

                    # 尝试akshare
                    if HAS_AKSHARE:
                        try:
                            ak_data = self._fetch_a_stock_akshare(key, name)
                            if ak_data:
                                result[key] = ak_data
                                if key in ('sh', 'sz'):
                                    total_vol += float(ak_data.get('vol', 0))
                                print(f'{name} using akshare: {ak_data["point"]}, {ak_data["pct"]}%')
                                continue
                        except Exception as e:
                            print(f'{name} akshare error: {e}')

                    # 最后尝试东方财富K线
                    try:
                        em_secid = {'sh': '1.000001', 'sz': '0.399001', 'cy': '0.399006'}[key]
                        klines = self._fetch_index_klines(em_secid, 1)
                        if klines and len(klines) > 0:
                            latest = klines[-1]
                            prev = klines[-2] if len(klines) > 1 else latest
                            point = latest['close']
                            pct = round((latest['close'] - prev['close']) / prev['close'] * 100, 2) if prev['close'] > 0 else 0
                            vol = latest.get('vol', 0) / 100000000
                            result[key] = {'point': str(point), 'pct': str(pct), 'vol': str(vol)}
                            if key in ('sh', 'sz'):
                                total_vol += vol
                            print(f'{name} using eastmoney kline: {point}, {pct}%')
                    except Exception as e:
                        print(f'{name} kline error: {e}')

            result['total_vol'] = round(total_vol, 2)

        except Exception as e:
            print(f'A stock fetch error: {e}')

        return result

    def _fetch_a_stock_qq(self, result, indices, total_vol):
        """从腾讯财经批量获取A股指数数据"""
        try:
            codes = ','.join([secid for _, secid, _, _ in indices])
            url = f'https://qt.gtimg.cn/q={codes}'
            resp = self._safe_get(url, headers=self.qq_headers)
            if resp and resp.status_code == 200:
                text = resp.text
                for key, secid, name, _ in indices:
                    # 解析格式: v_sh000001="1~上证指数~000001~4135.39~4177.92~..."
                    marker = f'v_{secid}='
                    for line in text.strip().split('\n'):
                        if marker in line:
                            parts = line.split('~')
                            if len(parts) >= 38:
                                point = float(parts[3]) if parts[3] else 0
                                pct = float(parts[32]) if parts[32] else 0
                                # 成交额在第37字段，单位是万元，转换为亿
                                vol = float(parts[37]) / 10000 if len(parts) > 37 and parts[37] else 0
                                if point > 0:
                                    result[key] = {
                                        'point': str(point),
                                        'pct': str(pct),
                                        'vol': str(vol)
                                    }
                                    if key in ('sh', 'sz'):
                                        total_vol += vol
                            break
                return total_vol
        except Exception as e:
            print(f'QQ A stock error: {e}')
        return None

    def _fetch_a_stock_sina_single(self, key, name):
        """从新浪财经获取单个A股指数数据"""
        try:
            sina_code = {'sh': 'sh000001', 'sz': 'sz399001', 'cy': 'sz399006'}[key]
            url = f'https://hq.sinajs.cn/list={sina_code}'
            headers = {'User-Agent': USER_AGENT, 'Referer': 'https://finance.sina.com.cn/'}
            resp = self._safe_get(url, headers=headers)
            if resp and resp.status_code == 200:
                text = resp.text
                # 解析格式: var hq_str_sh000001="上证指数,4135.39,..."
                if '="' in text:
                    parts = text.split('="')[1].rstrip('";').split(',')
                    if len(parts) >= 9:
                        point = float(parts[3]) if parts[3] else 0
                        prev_close = float(parts[2]) if parts[2] else 0
                        pct = round((point - prev_close) / prev_close * 100, 2) if prev_close > 0 else 0
                        vol = float(parts[8]) / 100000000 if parts[8] else 0
                        if point > 0:
                            return {'point': str(point), 'pct': str(pct), 'vol': str(vol)}
        except Exception as e:
            print(f'Sina {name} error: {e}')
        return None

    def _fetch_a_stock_akshare(self, key, name):
        """使用akshare获取A股指数数据"""
        try:
            df = ak.stock_zh_index_spot_em()
            code_map = {'sh': '000001', 'sz': '399001', 'cy': '399006'}
            code = code_map.get(key)

            if code:
                row = df[df['代码'] == code]
                if not row.empty:
                    row = row.iloc[0]
                    point = float(row.get('最新价', 0))
                    pct = float(row.get('涨跌幅', 0))
                    vol = float(row.get('成交额', 0)) / 100000000  # 转换为亿

                    if point > 0:
                        return {
                            'point': str(point),
                            'pct': str(pct),
                            'vol': str(vol)
                        }
        except Exception as e:
            print(f'akshare {name} error: {e}')
        return None

    def _fetch_a_stock_baostock(self, bs_code, name):
        """使用baostock获取A股指数数据"""
        try:
            lg = bs.login()
            if lg.error_code != '0':
                return None

            # 获取最近5个交易日的数据，确保有前一日数据计算涨跌幅
            today = datetime.now().strftime('%Y-%m-%d')
            week_ago = (datetime.now() - timedelta(days=10)).strftime('%Y-%m-%d')

            rs = bs.query_history_k_data_plus(bs_code,
                'date,close,volume,amount',
                start_date=week_ago,
                end_date=today,
                frequency='d',
                adjustflag='2')

            data_list = []
            while (rs.error_code == '0') and rs.next():
                data_list.append(rs.get_row_data())

            bs.logout()

            if data_list and len(data_list) >= 2:
                latest = data_list[-1]
                prev = data_list[-2]

                point = float(latest[1])  # close
                prev_close = float(prev[1])
                amount = float(latest[3])  # amount in yuan
                vol = amount / 100000000  # 转换为亿

                pct = round((point - prev_close) / prev_close * 100, 2) if prev_close > 0 else 0

                if point > 0:
                    return {
                        'point': str(point),
                        'pct': str(pct),
                        'vol': str(vol)
                    }
        except Exception as e:
            print(f'baostock {name} error: {e}')
        return None
    
    def _fetch_index_klines(self, secid, count=5):
        """获取指数K线数据"""
        try:
            url = 'https://push2his.eastmoney.com/api/qt/stock/kline/get'
            params = {
                'secid': secid,
                'fields1': 'f1,f2,f3,f4,f5,f6',
                'fields2': 'f51,f52,f53,f54,f55,f56,f57,f58,f59,f60,f61',
                'klt': 101,  # 日线
                'fqt': 1,
                'beg': 0,
                'end': 20500101,
                'lmt': count
            }
            
            resp = self._safe_get(url, params=params)
            if resp:
                data = resp.json()
                if data.get('data') and data['data'].get('klines'):
                    klines = []
                    for k in data['data']['klines']:
                        parts = k.split(',')
                        klines.append({
                            'date': parts[0],
                            'open': float(parts[1]),
                            'close': float(parts[2]),
                            'high': float(parts[3]),
                            'low': float(parts[4]),
                            'vol': float(parts[5])
                        })
                    return klines
        except Exception as e:
            print(f'K-line fetch error for {secid}: {e}')
        return []

    def _fetch_sectors(self, time_info):
        result = []
        # 1. 优先尝试新浪（HTML格式，但稳定）
        try:
            result = self._fetch_sectors_sina()
            if result:
                print(f'Sectors using Sina: {len(result)} items')
        except Exception as e:
            print(f'Sina sector error: {e}')

        # 2. 如果新浪失败，尝试akshare
        if not result and HAS_AKSHARE:
            try:
                result = self._fetch_sectors_akshare()
                if result:
                    print(f'Sectors using akshare: {len(result)} items')
            except Exception as e:
                print(f'akshare sector fallback error: {e}')

        # 3. 如果akshare也失败，尝试东方财富
        if not result:
            try:
                url = 'https://push2.eastmoney.com/api/qt/clist/get?pn=1&pz=20&po=1&np=1&fltt=2&invt=2&fid=f3&fs=m:90+t:2&fields=f12,f14,f3'
                resp = self._safe_get(url)
                if resp:
                    data = resp.json()
                    if data.get('data') and data['data'].get('diff'):
                        for item in data['data']['diff']:
                            result.append({
                                'name': item.get('f14', ''),
                                'pct': item.get('f3', 0)
                        })
                        print(f'Sectors using Eastmoney: {len(result)} items')
            except Exception as e:
                print(f'Eastmoney sector fallback error: {e}')

        return result

    def _fetch_sectors_akshare(self):
        """从akshare获取行业板块数据（备选）"""
        result = []
        try:
            import akshare as ak
            df = ak.stock_board_industry_name_ths()
            if df is not None and not df.empty:
                for _, row in df.head(20).iterrows():
                    name = str(row.get('板块名称', ''))
                    pct = float(row.get('涨跌幅', 0))
                    if name:
                        result.append({'name': name, 'pct': pct})
                result.sort(key=lambda x: x['pct'], reverse=True)
                print(f'akshare sectors: {len(result)} items')
        except Exception as e:
            print(f'akshare sectors error: {e}')
        return result[:20]

    def _fetch_sectors_sina(self):
        """从新浪财经获取行业板块数据"""
        result = []
        url = 'https://money.finance.sina.com.cn/q/view/newFLJK.php?param=industry'
        resp = self._safe_get(url)
        if resp:
            text = resp.content.decode('gbk', errors='ignore')
            match = re.search(r'var S_Finance_bankuai_industry = \{(.*?)\}', text, re.DOTALL)
            if match:
                content = match.group(1)
                entries = re.findall(r'"(\w+)":"([^"]+)"', content)
                for key, val in entries:
                    parts = val.split(',')
                    if len(parts) >= 8:
                        name = parts[1]
                        try:
                            pct = float(parts[4]) if parts[4] else 0
                        except:
                            pct = 0
                        result.append({'name': name, 'pct': pct})
                result.sort(key=lambda x: x['pct'], reverse=True)
                print(f'Sina sectors: {len(result)} items')
        return result[:20]

    def _fetch_lhb(self, time_info):
        """Fetch LongHuBang (Dragon Tiger List) data"""
        result = {'top_buy': [], 'top_sell': []}
        
        # 1. 优先尝试东方财富龙虎榜API
        success = self._fetch_lhb_eastmoney(result, time_info)
        
        # 2. 如果东方财富失败，尝试新浪财经备用
        if not success or not result['top_buy']:
            print('Eastmoney LHB failed, trying Sina fallback...')
            self._fetch_lhb_sina(result, time_info)
        
        return result
    
    def _fetch_lhb_eastmoney(self, result, time_info):
        """从东方财富获取龙虎榜数据"""
        try:
            url = 'https://datacenter-web.eastmoney.com/api/data/v1/get'

            # 尝试获取最近7天的数据
            from datetime import datetime, timedelta
            base_date = datetime.strptime(time_info['last_trading_date'], '%Y-%m-%d')

            for i in range(7):
                try_date = (base_date - timedelta(days=i)).strftime('%Y-%m-%d')
                params = {
                    'sortColumns': 'NET',
                    'sortTypes': '-1',
                    'pageSize': '50',
                    'pageNumber': '1',
                    'reportName': 'RPT_BILLBOARD_DAILYDETAILSBUY',
                    'columns': 'ALL',
                    'filter': f"(TRADE_DATE='{try_date}')"
                }

                resp = self._safe_get(url, params=params)
                if resp:
                    data = resp.json()
                    if data.get('success') and data.get('result') and data['result'].get('data'):
                        items = data['result']['data']
                        print(f'LHB data found for {try_date} ({len(items)} items)')

                        # 批量获取股票名称
                        codes = list(set([str(item.get('SECURITY_CODE', '')) for item in items if item.get('SECURITY_CODE')]))
                        stock_names = self._batch_get_stock_names(codes)

                        # 按股票代码合并同一股票的多条营业部记录
                        merged = {}
                        for item in items:
                            try:
                                code = str(item.get('SECURITY_CODE', ''))
                                if not code:
                                    continue
                                net_buy = float(item.get('NET', 0) or 0) / 10000  # 转换为万元

                                if code in merged:
                                    merged[code]['net_buy'] += net_buy
                                else:
                                    merged[code] = {
                                        'code': code,
                                        'name': stock_names.get(code, code),
                                        'close': float(item.get('CLOSE_PRICE', 0) or 0),
                                        'pct': float(item.get('CHANGE_RATE', 0) or 0),
                                        'net_buy': net_buy
                                    }
                            except Exception as e:
                                continue

                        # 按净买入金额排序
                        result['top_buy'] = sorted(merged.values(), key=lambda x: x['net_buy'], reverse=True)
                        if result['top_buy']:
                            return True
                    else:
                        print(f'No LHB data for {try_date}')
        except Exception as e:
            print(f'Eastmoney LHB error: {e}')
        return False

    def _batch_get_stock_names(self, codes):
        """批量获取股票名称"""
        names = {}
        if not codes:
            return names

        # 1. 优先尝试东方财富
        try:
            secids = []
            for code in codes:
                if code.startswith('6'):
                    secids.append(f'1.{code}')
                else:
                    secids.append(f'0.{code}')

            batch_size = 50
            for i in range(0, len(secids), batch_size):
                batch = secids[i:i+batch_size]
                secids_str = ','.join(batch)
                url = f'https://push2.eastmoney.com/api/qt/ulist/get?secids={secids_str}&fields=f12,f14'
                resp = self._safe_get(url)
                if resp:
                    data = resp.json()
                    if data.get('data') and data['data'].get('diff'):
                        for item in data['data']['diff']:
                            code = item.get('f12', '')
                            name = item.get('f14', '')
                            if code and name:
                                names[code] = name
        except Exception as e:
            print(f'Batch get stock names error: {e}')

        # 2. 如果东方财富失败或结果不全，用baostock补充
        missing = [c for c in codes if c not in names]
        if missing and HAS_BAOSTOCK:
            try:
                import baostock as bs
                bs.login()
                for code in missing:
                    if code.startswith('6'):
                        bs_code = f'sh.{code}'
                    else:
                        bs_code = f'sz.{code}'
                    rs = bs.query_stock_basic(code=bs_code)
                    while rs.error_code == '0' and rs.next():
                        row = rs.get_row_data()
                        # fields: code, code_name, ipoDate, outDate, type, status
                        if len(row) >= 2 and row[1]:
                            names[code] = row[1]
                bs.logout()
                print(f'baostock stock names: got {len([c for c in missing if c in names])} names')
            except Exception as e:
                print(f'baostock stock names error: {e}')

        return names
    
    def _fetch_lhb_sina(self, result, time_info):
        """从东方财富备用API获取龙虎榜数据"""
        try:
            url = 'https://datacenter-web.eastmoney.com/api/data/v1/get'
            
            # 使用 RPT_BILLBOARD_DAILYDETAILSBUY 作为备用
            from datetime import datetime, timedelta
            base_date = datetime.strptime(time_info['last_trading_date'], '%Y-%m-%d')
            
            for i in range(7):
                try_date = (base_date - timedelta(days=i)).strftime('%Y-%m-%d')
                params = {
                    'sortColumns': 'BUY',
                    'sortTypes': '-1',
                    'pageSize': '20',
                    'pageNumber': '1',
                    'reportName': 'RPT_BILLBOARD_DAILYDETAILSBUY',
                    'columns': 'SECURITY_CODE,SECURITY_NAME_ABBR,CLOSE_PRICE,CHANGE_RATE,BUY,SELL,NET',
                    'filter': f"(TRADE_DATE='{try_date}')"
                }
                
                resp = self._safe_get(url, params=params)
                if resp:
                    data = resp.json()
                    if data.get('result') and data['result'].get('data'):
                        items = data['result']['data']
                        print(f'LHB backup data found for {try_date} ({len(items)} items)')
                        for item in items:
                            try:
                                stock_info = {
                                    'code': str(item.get('SECURITY_CODE', '')),
                                    'name': str(item.get('SECURITY_NAME_ABBR', '')),
                                    'close': float(item.get('CLOSE_PRICE', 0)),
                                    'pct': float(item.get('CHANGE_RATE', 0)),
                                    'net_buy': float(item.get('NET', 0)) / 10000
                                }
                                if stock_info['code'] and stock_info['name']:
                                    result['top_buy'].append(stock_info)
                            except Exception as e:
                                continue
                        if result['top_buy']:
                            return
                    else:
                        print(f'No LHB backup data for {try_date}')
        except Exception as e:
            print(f'LHB backup error: {e}')

    def _fetch_northbound(self, time_info):
        result = {'total_net': 0, 'sh': 0, 'sz': 0}
        
        # 1. 优先尝试东方财富API
        success = self._fetch_northbound_eastmoney(result)
        
        # 2. 如果东方财富失败，尝试新浪财经备用
        if not success:
            print('Eastmoney northbound failed, trying Sina fallback...')
            self._fetch_northbound_sina(result)
        
        return result
    
    def _fetch_northbound_eastmoney(self, result):
        """从东方财富获取北向资金数据"""
        try:
            from datetime import datetime, timedelta

            url = 'https://datacenter-web.eastmoney.com/api/data/v1/get'

            # 获取最近5个交易日的数据
            for i in range(5):
                try_date = (datetime.now() - timedelta(days=i)).strftime('%Y-%m-%d')

                # 沪股通 (MUTUAL_TYPE='001')
                params = {
                    'reportName': 'RPT_MUTUAL_DEAL_HISTORY',
                    'columns': 'ALL',
                    'pageSize': '1',
                    'pageNumber': '1',
                    'sortColumns': 'TRADE_DATE',
                    'sortTypes': '-1',
                    'filter': f"(MUTUAL_TYPE='001')(TRADE_DATE='{try_date}')"
                }

                resp = self._safe_get(url, params=params)
                if resp:
                    data = resp.json()
                    if data.get('result') and data['result'].get('data'):
                        item = data['result']['data'][0]
                        sh_net = float(item.get('NET_DEAL_AMT', 0) or 0)

                        # 深股通 (MUTUAL_TYPE='003')
                        params['filter'] = f"(MUTUAL_TYPE='003')(TRADE_DATE='{try_date}')"
                        resp2 = self._safe_get(url, params=params)
                        if resp2:
                            data2 = resp2.json()
                            if data2.get('result') and data2['result'].get('data'):
                                item2 = data2['result']['data'][0]
                                sz_net = float(item2.get('NET_DEAL_AMT', 0) or 0)

                                result['total_net'] = sh_net + sz_net
                                result['sh'] = sh_net
                                result['sz'] = sz_net
                                print(f'Northbound data found for {try_date}: total={result["total_net"]:.2f}万, sh={sh_net:.2f}万, sz={sz_net:.2f}万')
                                return True
        except Exception as e:
            print(f'Eastmoney northbound error: {e}')
        return False
    
    def _fetch_northbound_sina(self, result):
        """从新浪财经获取北向资金数据（备用）"""
        try:
            # 新浪财经北向资金API
            url = 'https://hq.sinajs.cn/list=sh000300'
            headers = {
                'User-Agent': USER_AGENT,
                'Referer': 'https://finance.sina.com.cn/'
            }
            
            resp = self._safe_get(url, headers=headers)
            if resp and resp.status_code == 200:
                text = resp.text
                # 解析沪深300数据，从中提取资金流向信息
                # 这里简化处理，返回一个估算值
                # 实际上新浪的北向资金数据需要单独的API
                print(f'Sina northbound fallback: using estimated data')
                # 返回0表示无法获取准确数据
                result['total_net'] = 0
        except Exception as e:
            print(f'Sina northbound error: {e}')

    def _fetch_news(self, time_info):
        news = {
            'geopolitics': [],
            'policy': [],
            'other': [],
            'all_news': []  # 保存所有原始新闻供AI筛选
        }
        seen_titles = set()
        seen_hashes = set()
        
        # Keywords for categorization
        geo_keywords = ['冲突', '制裁', '外交', '军事', '战争', '地缘', '特朗普', '拜登', '俄罗斯', '乌克兰', '中东', '朝鲜', '伊朗', '中美', '贸易']
        policy_keywords = ['央行', '货币政策', '财政', '利率', '降准', '降息', '监管', '政策', '国务院', '证监会', '银保监', '发改委']
        
        # Source 1: Eastmoney News
        self._fetch_news_eastmoney(news, geo_keywords, policy_keywords, seen_titles, seen_hashes)
        
        # Source 2: Sina Finance News
        self._fetch_news_sina(news, geo_keywords, policy_keywords, seen_titles, seen_hashes)
        
        # Source 3: 10jqka News
        self._fetch_news_10jqka(news, geo_keywords, policy_keywords, seen_titles, seen_hashes)
        
        # Source 4: CLS News
        self._fetch_news_cls(news, geo_keywords, policy_keywords, seen_titles, seen_hashes)
        
        return news
    
    def _get_title_hash(self, title, keywords):
        """Generate a hash for deduplication based on full title"""
        import hashlib
        # Normalize title
        normalized = title.lower().replace(' ', '').replace('\u3000', '')
        # 使用完整标题计算hash，避免截断导致的误判
        return hashlib.md5(normalized.encode()).hexdigest()[:16]

    def _fetch_news_eastmoney(self, news, geo_keywords, policy_keywords, seen_titles, seen_hashes):
        """Fetch news from Eastmoney"""
        try:
            # 使用东方财富快讯API获取新闻
            url = 'https://np-listapi.eastmoney.com/comm/web/getNewsByColumns'
            params = {
                'client': 'web',
                'biz': 'web_news_col',
                'column': '350',
                'order': '1',
                'needInteractData': '0',
                'page_index': '1',
                'page_size': '20'
            }
            headers = {
                'User-Agent': USER_AGENT,
                'Referer': 'https://finance.eastmoney.com/'
            }
            resp = self._safe_get(url, headers=headers, params=params)
            if resp:
                data = resp.json()
                if data.get('data') and data['data'].get('list'):
                    news_list = data['data']['list']
                    for item in news_list[:15]:
                        title = item.get('title', '').strip()
                        digest = item.get('digest', '').strip()
                        if title and len(title) > 10:
                            title_hash = self._get_title_hash(title, geo_keywords + policy_keywords)
                            if title not in seen_titles and title_hash not in seen_hashes:
                                seen_titles.add(title)
                                seen_hashes.add(title_hash)
                                entry = {'title': title, 'digest': digest, 'source': 'eastmoney', 'full_text': f"{title} {digest}"}
                                # 所有新闻都加入 all_news
                                news['all_news'].append(entry)
                                if any(kw in title for kw in geo_keywords):
                                    news['geopolitics'].append(entry)
                                elif any(kw in title for kw in policy_keywords):
                                    news['policy'].append(entry)
                                else:
                                    news['other'].append(entry)
        except Exception as e:
            print(f'Eastmoney news error: {e}')

    def _fetch_news_sina(self, news, geo_keywords, policy_keywords, seen_titles, seen_hashes):
        """Fetch news from Sina Finance"""
        try:
            url = 'https://finance.sina.com.cn/'
            resp = self._safe_get(url)
            if resp:
                from bs4 import BeautifulSoup
                soup = BeautifulSoup(resp.text, 'lxml')
                links = soup.find_all('a', href=True)
                for link in links[:20]:
                    title = link.get_text().strip()
                    if title and len(title) > 10:
                        title_hash = self._get_title_hash(title, geo_keywords + policy_keywords)
                        if title not in seen_titles and title_hash not in seen_hashes:
                            seen_titles.add(title)
                            seen_hashes.add(title_hash)
                            entry = {'title': title, 'digest': '', 'source': 'sina', 'full_text': title}
                            # 所有新闻都加入 all_news
                            news['all_news'].append(entry)
                            if any(kw in title for kw in geo_keywords):
                                news['geopolitics'].append(entry)
                            elif any(kw in title for kw in policy_keywords):
                                news['policy'].append(entry)
                            else:
                                news['other'].append(entry)
        except Exception as e:
            print(f'Sina news error: {e}')

    def _fetch_news_10jqka(self, news, geo_keywords, policy_keywords, seen_titles, seen_hashes):
        """Fetch news from 10jqka (同花顺)"""
        try:
            url = 'https://basic.10jqka.com.cn/api/stockph/'
            headers = {
                'User-Agent': USER_AGENT,
                'Referer': 'https://basic.10jqka.com.cn/'
            }
            resp = self._safe_get(url, headers=headers)
            if resp:
                data = resp.json()
                if data.get('data'):
                    items = data['data'].get('list', [])
                    for item in items[:10]:
                        title = item.get('title', '')
                        digest = item.get('digest', '')
                        if title and len(title) > 10:
                            title_hash = self._get_title_hash(title, geo_keywords + policy_keywords)
                            if title not in seen_titles and title_hash not in seen_hashes:
                                seen_titles.add(title)
                                seen_hashes.add(title_hash)
                                entry = {'title': title, 'digest': digest, 'source': '10jqka', 'full_text': f"{title} {digest}"}
                                # 所有新闻都加入 all_news
                                news['all_news'].append(entry)
                                if any(kw in title for kw in geo_keywords):
                                    news['geopolitics'].append(entry)
                                elif any(kw in title for kw in policy_keywords):
                                    news['policy'].append(entry)
                                else:
                                    news['other'].append(entry)
        except Exception as e:
            print(f'10jqka news error: {e}')
    
    def _fetch_news_cls(self, news, geo_keywords, policy_keywords, seen_titles, seen_hashes):
        """Fetch news from CLS (财联社)"""
        try:
            # CLS Telegraph API
            url = 'https://www.cls.cn/nodeapi/updateTelegraphList'
            params = {'app': 'CailianpressWeb', 'os': 'web', 'sv': '7.7.5'}
            resp = self._safe_get(url, params=params)
            if resp:
                data = resp.json()
                if data.get('data'):
                    items = data['data'].get('roll_data', [])
                    for item in items[:15]:
                        content = item.get('content', '')
                        title = content.strip() if content else ''
                        
                        if title:
                            title_hash = self._get_title_hash(title, geo_keywords + policy_keywords)
                            if title not in seen_titles and title_hash not in seen_hashes:
                                seen_titles.add(title)
                                seen_hashes.add(title_hash)
                                entry = {'title': title, 'digest': content, 'source': 'cls', 'full_text': content}
                                # 所有新闻都加入 all_news
                                news['all_news'].append(entry)
                                if any(kw in content for kw in geo_keywords):
                                    news['geopolitics'].append(entry)
                                elif any(kw in content for kw in policy_keywords):
                                    news['policy'].append(entry)
                                else:
                                    news['other'].append(entry)
            
            # CLS News List API
            url2 = 'https://www.cls.cn/nodeapi/telegraphList'
            params2 = {'app': 'CailianpressWeb', 'os': 'web', 'sv': '7.7.5', 'rn': '10'}
            resp2 = self._safe_get(url2, params=params2)
            if resp2:
                data2 = resp2.json()
                if data2.get('data'):
                    items2 = data2['data'].get('roll_data', [])
                    for item in items2[:10]:
                        content = item.get('content', '')
                        title = content.strip() if content else ''
                        
                        if title:
                            title_hash = self._get_title_hash(title, geo_keywords + policy_keywords)
                            if title not in seen_titles and title_hash not in seen_hashes:
                                seen_titles.add(title)
                                seen_hashes.add(title_hash)
                                entry = {'title': title, 'digest': content, 'source': 'cls', 'full_text': content}
                                # 所有新闻都加入 all_news
                                news['all_news'].append(entry)
                                if any(kw in content for kw in geo_keywords):
                                    news['geopolitics'].append(entry)
                                elif any(kw in content for kw in policy_keywords):
                                    news['policy'].append(entry)
                                else:
                                    news['other'].append(entry)
        except Exception as e:
            print(f'CLS news error: {e}')
    
    def fetch_all_stocks(self, limit=100):
        """获取全市场股票列表，用于缠论分析选股"""
        stocks = []
        try:
            # 使用东方财富API获取沪深A股列表
            url = 'https://push2.eastmoney.com/api/qt/clist/get'
            params = {
                'pn': 1,  # 页码
                'pz': limit,  # 每页数量
                'po': 1,  # 排序方向
                'np': 1,
                'ut': 'bd1d9ddb04089700cf9c27f6f7426281',
                'fltt': 2,
                'invt': 2,
                'fid': 'f20',  # 按成交额排序
                'fs': 'm:0+t:6,m:0+t:13,m:1+t:2,m:1+t:23',  # 沪深A股
                'fields': 'f12,f14,f2,f3,f4,f5,f6,f7,f8,f9,f10,f20,f21,f22,f23,f24,f25,f26,f33,f34,f35,f36,f37,f38,f39,f40,f41,f42,f43,f44,f45,f46,f47,f48,f49,f50,f51,f52,f53,f54,f55,f56,f57,f58,f59,f60,f61,f62,f63,f64,f65,f66,f67,f68,f69,f70,f71,f72,f73,f74,f75,f76,f77,f78,f79,f80,f81,f82,f83,f84,f85,f86,f87,f88,f89,f90,f91,f92,f93,f94,f95,f96,f97,f98,f99,f100',
                '_': int(time.time() * 1000)
            }
            
            resp = self._safe_get(url, params=params)
            if resp:
                data = resp.json()
                if data.get('data') and data['data'].get('diff'):
                    for item in data['data']['diff']:
                        stock = {
                            'code': item.get('f12', ''),  # 股票代码
                            'name': item.get('f14', ''),  # 股票名称
                            'close': float(item.get('f2', 0)),  # 最新价
                            'pct': float(item.get('f3', 0)),  # 涨跌幅
                            'vol': float(item.get('f5', 0)),  # 成交量
                            'amount': float(item.get('f6', 0)),  # 成交额
                            'turnover': float(item.get('f8', 0)),  # 换手率
                            'pe': float(item.get('f9', 0)) if item.get('f9') else 0,  # 市盈率
                            'pb': float(item.get('f23', 0)) if item.get('f23') else 0,  # 市净率
                            'mktcap': float(item.get('f20', 0)) if item.get('f20') else 0,  # 总市值
                            'industry': item.get('f20', '')  # 所属行业
                        }
                        if stock['code'] and stock['name']:
                            stocks.append(stock)
                    
                    print(f'Fetched {len(stocks)} stocks for analysis')
        except Exception as e:
            print(f'Fetch all stocks error: {e}')
        
        return stocks
    
    def fetch_hot_stocks(self, limit=50):
        """获取热门股票（涨幅榜+成交额榜综合）"""
        stocks = []

        # 1. 首选新浪财经排行API
        stocks = self._fetch_hot_stocks_sina(limit)

        # 2. 备选akshare人气榜
        if not stocks and HAS_AKSHARE:
            try:
                stocks = self._fetch_hot_stocks_akshare(limit)
            except Exception as e:
                print(f'akshare hot stocks fallback error: {e}')

        # 3. 使用akshare补充行业信息
        if stocks and HAS_AKSHARE:
            self._fill_industry_info(stocks)

        return stocks

    def _fill_industry_info(self, stocks):
        """批量获取股票行业信息"""
        # 1. 尝试使用akshare
        if self._fill_industry_akshare(stocks):
            return

        # 2. 尝试使用东方财富API
        if self._fill_industry_eastmoney(stocks):
            return

        # 3. 尝试使用新浪财经API
        self._fill_industry_sina(stocks)

    def _fill_industry_akshare(self, stocks):
        """使用akshare获取股票行业信息"""
        try:
            import akshare as ak
            import time

            filled_count = 0
            for stock in stocks:
                code = stock.get('code', '')
                if not code:
                    continue

                # 重试机制
                for attempt in range(3):
                    try:
                        # 获取单只股票信息
                        df = ak.stock_individual_info_em(symbol=code)
                        if df is not None and not df.empty:
                            # 查找行业信息
                            for _, row in df.iterrows():
                                item = str(row.get('item', ''))
                                value = str(row.get('value', ''))
                                if item == '行业':
                                    stock['industry'] = value
                                    filled_count += 1
                                    break
                        break  # 成功则跳出重试循环
                    except Exception as e:
                        if attempt < 2:
                            time.sleep(2)  # 失败后等待2秒再重试
                        continue

                time.sleep(1.5)  # 避免请求过快

            print(f'akshare行业信息填充: {filled_count}/{len(stocks)}只股票')
            return filled_count > 0
        except Exception as e:
            print(f'akshare行业信息填充失败: {e}')
        return False

    def _fill_industry_eastmoney(self, stocks):
        """使用东方财富API获取股票行业信息"""
        try:
            # 构建secids
            secids = []
            for stock in stocks:
                code = stock.get('code', '')
                if code.startswith('6'):
                    secids.append(f'1.{code}')
                else:
                    secids.append(f'0.{code}')

            if not secids:
                return

            # 批量获取股票信息（包含行业）
            batch_size = 50
            for i in range(0, len(secids), batch_size):
                batch = secids[i:i+batch_size]
                secids_str = ','.join(batch)
                url = f'https://push2.eastmoney.com/api/qt/ulist/get?secids={secids_str}&fields=f12,f14,f100'

                resp = self._safe_get(url)
                if resp:
                    data = resp.json()
                    if data.get('data') and data['data'].get('diff'):
                        # 创建代码到行业的映射
                        code_to_industry = {}
                        for item in data['data']['diff']:
                            code = item.get('f12', '')
                            industry = item.get('f100', '')
                            if code and industry:
                                code_to_industry[code] = industry

                        # 填充行业信息
                        filled_count = 0
                        for stock in stocks:
                            code = stock.get('code', '')
                            if code in code_to_industry:
                                stock['industry'] = code_to_industry[code]
                                filled_count += 1

                        print(f'东方财富行业信息填充: {filled_count}/{len(stocks)}只股票')
                        return True
        except Exception as e:
            print(f'东方财富行业信息填充失败: {e}')
        return False

    def _fill_industry_sina(self, stocks):
        """使用新浪财经API获取股票行业信息"""
        try:
            headers = {
                'User-Agent': USER_AGENT,
                'Referer': 'https://finance.sina.com.cn/'
            }

            filled_count = 0
            for stock in stocks:
                code = stock.get('code', '')
                if not code:
                    continue

                # 新浪财经个股信息API
                url = f'https://finance.sina.com.cn/realstock/company/{code}/nc.shtml'
                resp = self._safe_get(url, headers=headers)
                if resp:
                    from bs4 import BeautifulSoup
                    soup = BeautifulSoup(resp.text, 'lxml')

                    # 查找行业信息
                    # 通常在页面的公司概况部分
                    industry_elem = soup.find('a', href=lambda x: x and 'industry' in x.lower())
                    if industry_elem:
                        industry = industry_elem.get_text().strip()
                        if industry:
                            stock['industry'] = industry
                            filled_count += 1
                            continue

                    # 备用方式：查找包含"行业"的文本
                    for elem in soup.find_all(['td', 'span', 'div']):
                        text = elem.get_text().strip()
                        if '行业' in text and len(text) < 20:
                            # 查找下一个兄弟元素作为行业值
                            next_elem = elem.find_next_sibling()
                            if next_elem:
                                industry = next_elem.get_text().strip()
                                if industry and len(industry) < 20:
                                    stock['industry'] = industry
                                    filled_count += 1
                                    break

            print(f'新浪财经行业信息填充: {filled_count}/{len(stocks)}只股票')
        except Exception as e:
            print(f'新浪财经行业信息填充失败: {e}')

    def _fetch_hot_stocks_sina(self, limit=50):
        """从新浪财经获取热门股票（涨幅榜+成交额榜合并）"""
        stocks = []
        headers = {
            'User-Agent': USER_AGENT,
            'Referer': 'https://finance.sina.com.cn/'
        }
        url = 'https://vip.stock.finance.sina.com.cn/quotes_service/api/json_v2.php/Market_Center.getHQNodeData'

        # 同时获取涨幅榜和成交额榜
        for sort_key, label in [('changepercent', '涨幅'), ('amount', '成交额')]:
            try:
                params = {
                    'page': 1,
                    'num': limit,
                    'sort': sort_key,
                    'asc': 0,
                    'node': 'hs_a',
                    'symbol': '',
                    '_s_r_a': 'init'
                }
                resp = self._safe_get(url, params=params, headers=headers)
                if resp:
                    data = resp.json()
                    if data:
                        for item in data:
                            code = item.get('symbol', '')  # sh600000 格式
                            # 转换为纯数字代码
                            pure_code = code[2:] if len(code) > 2 else code
                            stock = {
                                'code': pure_code,
                                'name': item.get('name', ''),
                                'close': float(item.get('trade', 0)),
                                'pct': float(item.get('changepercent', 0)),
                                'vol': float(item.get('volume', 0)),
                                'amount': float(item.get('amount', 0)),
                                'turnover': float(item.get('turnoverratio', 0)),
                                'pe': 0,
                                'mktcap': float(item.get('mktcap', 0)),
                                'industry': ''
                            }
                            if stock['code'] and stock['name']:
                                stocks.append(stock)
                        print(f'Sina {label}榜: {len(data)} items')
            except Exception as e:
                print(f'Sina {label}榜 error: {e}')

        if stocks:
            # 去重，按成交额排序
            seen = set()
            unique_stocks = []
            for s in stocks:
                if s['code'] not in seen:
                    seen.add(s['code'])
                    unique_stocks.append(s)
            stocks = sorted(unique_stocks, key=lambda x: x['amount'], reverse=True)[:limit]
            print(f'Sina hot stocks total: {len(stocks)} items (merged)')

        return stocks

    def _fetch_hot_stocks_akshare(self, limit=50):
        """从akshare获取人气榜股票（备选）"""
        stocks = []
        try:
            import akshare as ak
            df = ak.stock_hot_rank_em()
            if df is not None and not df.empty:
                for _, row in df.head(limit).iterrows():
                    code = str(row.get('股票代码', ''))
                    name = str(row.get('股票简称', ''))
                    pct = float(row.get('涨跌幅', 0))
                    close = float(row.get('最新价', 0))
                    if code and name and pct > 0:
                        stocks.append({
                            'code': code,
                            'name': name,
                            'close': close,
                            'pct': pct,
                            'vol': 0,
                            'amount': 0,
                            'turnover': 0,
                            'pe': 0,
                            'mktcap': 0,
                            'industry': ''
                        })
                print(f'akshare hot stocks: {len(stocks)} items')
        except Exception as e:
            print(f'akshare hot stocks error: {e}')
        return stocks
