#!/usr/bin/env python3
import requests
from bs4 import BeautifulSoup
import json
import re
import time
import os
from datetime import datetime, timedelta
from config.settings import USER_AGENT, REQUEST_TIMEOUT, REQUEST_INTERVAL

# 可选数据源库
try:
    import baostock as bs
    HAS_BAOSTOCK = True
except ImportError:
    HAS_BAOSTOCK = False

try:
    import akshare as ak
    HAS_AKSHARE = True
except ImportError:
    HAS_AKSHARE = False

try:
    import finnhub
    FINNHUB_API_KEY = os.getenv('FINNHUB_API_KEY', '')
    HAS_FINNHUB = bool(FINNHUB_API_KEY)
except ImportError:
    HAS_FINNHUB = False
    FINNHUB_API_KEY = ''

# Twelve Data API (免费额度，需要注册获取API key)
TWELVEDATA_API_KEY = os.getenv('TWELVEDATA_API_KEY', '')
HAS_TWELVEDATA = bool(TWELVEDATA_API_KEY)

class DataFetcher:
    def __init__(self):
        self.headers = {'User-Agent': USER_AGENT}
        self.session = requests.Session()
        self.session.headers.update(self.headers)

    def fetch_all_data(self, time_info):
        data = {}
        data['us_stock'] = self._fetch_us_stock(time_info)
        time.sleep(REQUEST_INTERVAL)
        data['commodity'] = self._fetch_commodity(time_info)
        time.sleep(REQUEST_INTERVAL)
        data['a_stock'] = self._fetch_a_stock(time_info)
        time.sleep(REQUEST_INTERVAL)
        data['sectors'] = self._fetch_sectors(time_info)
        time.sleep(REQUEST_INTERVAL)
        data['lhb'] = self._fetch_lhb(time_info)
        time.sleep(REQUEST_INTERVAL)
        data['northbound'] = self._fetch_northbound(time_info)
        data['news'] = self._fetch_news(time_info)
        return data

    def _safe_get(self, url, max_retries=2, **kwargs):
        for attempt in range(max_retries):
            try:
                resp = self.session.get(url, timeout=REQUEST_TIMEOUT, **kwargs)
                resp.encoding = resp.apparent_encoding or 'utf-8'
                return resp
            except Exception as e:
                if attempt < max_retries - 1:
                    time.sleep(1)
                    continue
                print(f'Request failed: {url[:60]}... - {e}')
                return None

    def _fetch_us_stock(self, time_info):
        result = {'djia':{}, 'nasdaq':{}, 'sp500':{}, 'summary':''}
        try:
            # 1. 优先尝试东方财富API
            indices = [('djia','100.DJIA'),('nasdaq','100.NDX'),('sp500','100.SPX')]
            success_count = 0

            for key, secid in indices:
                url = f'https://push2.eastmoney.com/api/qt/stock/get?secid={secid}&fields=f43,f44,f45,f46,f47,f170,f48'
                resp = self._safe_get(url)
                if resp:
                    d = resp.json().get('data')
                    if d and d.get('f43'):
                        result[key] = {
                            'point': str(d.get('f43', 0) / 100),
                            'pct': str(d.get('f170', 0) / 100),
                            'note': ''
                        }
                        success_count += 1

            # 2. 如果东方财富失败，尝试新浪财经备用API
            if success_count == 0:
                print('Eastmoney US stock API failed, trying Sina Finance fallback...')
                self._fetch_us_stock_sina(result)

            # 3. 如果新浪也失败，尝试Twelve Data
            if success_count == 0 and HAS_TWELVEDATA:
                sina_success = any(result[k].get('point') for k in ['djia', 'nasdaq', 'sp500'])
                if not sina_success:
                    print('Sina US stock failed, trying Twelve Data fallback...')
                    self._fetch_us_stock_twelvedata(result)

            # 4. 如果Twelve Data也失败，尝试finnhub
            if success_count == 0 and HAS_FINNHUB:
                td_success = any(result[k].get('point') for k in ['djia', 'nasdaq', 'sp500'])
                if not td_success:
                    print('Twelve Data failed, trying finnhub fallback...')
                    self._fetch_us_stock_finnhub(result)

            # Summary will be generated by AI later
            result['summary'] = ''
        except Exception as e:
            print(f'US stock fetch error: {e}')
            # Fallback to Sina Finance on any error
            self._fetch_us_stock_sina(result)
        return result
    
    def _fetch_us_stock_sina(self, result):
        """Fetch US stock data from Sina Finance - fallback"""
        try:
            headers = {
                'User-Agent': USER_AGENT,
                'Referer': 'https://finance.sina.com.cn/'
            }
            # 新浪财经美股代码：道琼斯=gb_dji, 纳斯达克=gb_ixic, 标普500=gb_inx
            url = 'https://hq.sinajs.cn/list=gb_dji,gb_ixic,gb_inx'
            resp = self._safe_get(url, headers=headers)
            
            if resp:
                text = resp.text
                lines = text.strip().split('\n')
                for line in lines:
                    line = line.strip()
                    # 解析道琼斯
                    if line.startswith('var hq_str_gb_dji'):
                        # 格式: var hq_str_gb_dji="道琼斯,49693.1992,-0.14,2026-05-14 04:55:44,...
                        parts = line.split('="')[1].rstrip('";').split(',')
                        if len(parts) >= 3:
                            result['djia'] = {
                                'point': parts[1],  # 点位
                                'pct': parts[2],    # 涨跌幅
                                'note': ''
                            }
                    # 解析纳斯达克
                    elif line.startswith('var hq_str_gb_ixic'):
                        parts = line.split('="')[1].rstrip('";').split(',')
                        if len(parts) >= 3:
                            result['nasdaq'] = {
                                'point': parts[1],
                                'pct': parts[2],
                                'note': ''
                            }
                    # 解析标普500
                    elif line.startswith('var hq_str_gb_inx'):
                        parts = line.split('="')[1].rstrip('";').split(',')
                        if len(parts) >= 3:
                            result['sp500'] = {
                                'point': parts[1],
                                'pct': parts[2],
                                'note': ''
                            }
                print(f'Sina fallback success: DJIA={result["djia"].get("point",0)}, NASDAQ={result["nasdaq"].get("point",0)}, SPX={result["sp500"].get("point",0)}')
        except Exception as e:
            print(f'Sina US stock fallback error: {e}')

    def _fetch_us_stock_twelvedata(self, result):
        """使用Twelve Data获取美股数据"""
        try:
            # 美股指数代码
            indices = [
                ('djia', '^DJI'),
                ('nasdaq', '^IXIC'),
                ('sp500', '^GSPC')
            ]

            for key, symbol in indices:
                try:
                    url = 'https://api.twelvedata.com/time_series'
                    params = {
                        'symbol': symbol,
                        'interval': '1day',
                        'outputsize': '2',
                        'apikey': TWELVEDATA_API_KEY
                    }

                    resp = self._safe_get(url, params=params)
                    if resp:
                        data = resp.json()
                        if data.get('status') == 'ok' and data.get('values'):
                            values = data['values']
                            current = float(values[0]['close'])
                            prev = float(values[1]['close']) if len(values) > 1 else current
                            pct = round((current - prev) / prev * 100, 2) if prev > 0 else 0

                            result[key] = {
                                'point': str(current),
                                'pct': str(pct),
                                'note': ''
                            }
                            print(f'Twelve Data {key}: {current}, {pct}%')
                except Exception as e:
                    print(f'Twelve Data {key} error: {e}')

        except Exception as e:
            print(f'Twelve Data US stock error: {e}')

    def _fetch_us_stock_finnhub(self, result):
        """使用finnhub获取美股数据"""
        try:
            client = finnhub.Client(api_key=FINNHUB_API_KEY)

            # 美股指数代码
            indices = [
                ('djia', '^DJI'),
                ('nasdaq', '^IXIC'),
                ('sp500', '^GSPC')
            ]

            for key, symbol in indices:
                try:
                    quote = client.quote(symbol)
                    if quote and quote.get('c'):
                        current = quote['c']
                        prev_close = quote.get('pc', current)
                        pct = round((current - prev_close) / prev_close * 100, 2) if prev_close > 0 else 0

                        result[key] = {
                            'point': str(current),
                            'pct': str(pct),
                            'note': ''
                        }
                        print(f'Finnhub {key}: {current}, {pct}%')
                except Exception as e:
                    print(f'Finnhub {key} error: {e}')

        except Exception as e:
            print(f'Finnhub US stock error: {e}')

    def _fetch_commodity(self, time_info):
        result = {}
        
        # 1. 优先尝试东方财富API
        self._fetch_commodity_eastmoney(result)
        
        # 2. 对于失败的商品，尝试新浪财经备用
        for key in ['gold', 'wti', 'brent']:
            if key not in result or result.get(key, {}).get('need_ai'):
                print(f'Eastmoney {key} failed, trying Sina fallback...')
                self._fetch_commodity_sina(result, key)
        
        return result
    
    def _fetch_commodity_eastmoney(self, result):
        """从东方财富获取商品数据"""
        try:
            # Gold
            gold_resp = self._safe_get('https://push2.eastmoney.com/api/qt/stock/get?secid=101.GC00Y&fields=f43,f170')
            if gold_resp:
                resp_data = gold_resp.json()
                d = resp_data.get('data') if resp_data else None
                if d and d.get('f43'):
                    result['gold'] = {'price': str(d.get('f43', 0) / 100), 'pct': str(d.get('f170', 0) / 100)}
                else:
                    result['gold'] = {'price': None, 'pct': None, 'need_ai': True}
            else:
                result['gold'] = {'price': None, 'pct': None, 'need_ai': True}
            
            # WTI Crude
            wti_resp = self._safe_get('https://push2.eastmoney.com/api/qt/stock/get?secid=101.CL00Y&fields=f43,f170')
            if wti_resp:
                resp_data = wti_resp.json()
                d = resp_data.get('data') if resp_data else None
                if d and d.get('f43'):
                    result['wti'] = {'price': str(d.get('f43', 0) / 100), 'pct': str(d.get('f170', 0) / 100)}
                else:
                    result['wti'] = {'price': None, 'pct': None, 'need_ai': True}
            else:
                result['wti'] = {'price': None, 'pct': None, 'need_ai': True}
            
            # Brent Crude
            brent_resp = self._safe_get('https://push2.eastmoney.com/api/qt/stock/get?secid=101.B00Y&fields=f43,f170')
            if brent_resp:
                resp_data = brent_resp.json()
                d = resp_data.get('data') if resp_data else None
                if d and d.get('f43'):
                    result['brent'] = {'price': str(d.get('f43', 0) / 100), 'pct': str(d.get('f170', 0) / 100)}
                else:
                    result['brent'] = {'price': None, 'pct': None, 'need_ai': True}
            else:
                result['brent'] = {'price': None, 'pct': None, 'need_ai': True}
        except Exception as e:
            print(f'Eastmoney commodity error: {e}')
    
    def _fetch_commodity_sina(self, result, commodity_type):
        """从新浪财经获取商品数据（备用）"""
        try:
            # 新浪财经商品代码
            sina_codes = {
                'gold': 'hf_GC',  # 黄金
                'wti': 'hf_CL',   # WTI原油
                'brent': 'hf_OIL' # 布伦特原油
            }
            
            code = sina_codes.get(commodity_type)
            if not code:
                return
            
            url = f'https://hq.sinajs.cn/list={code}'
            headers = {
                'User-Agent': USER_AGENT,
                'Referer': 'https://finance.sina.com.cn/'
            }
            
            resp = self._safe_get(url, headers=headers)
            if resp and resp.status_code == 200:
                text = resp.text
                # 解析格式: var hq_str_xxx="价格,涨跌幅,..."
                if '="' in text:
                    parts = text.split('="')[1].rstrip('";').split(',')
                    if len(parts) >= 2:
                        try:
                            price = float(parts[0])
                            # 计算涨跌幅（如果有前一日收盘价）
                            pct = 0
                            if len(parts) > 7 and parts[7]:
                                prev_close = float(parts[7])
                                if prev_close > 0:
                                    pct = round((price - prev_close) / prev_close * 100, 2)
                            
                            result[commodity_type] = {'price': str(price), 'pct': str(pct)}
                            print(f'Sina {commodity_type} data: price={price}, pct={pct}%')
                        except Exception as e:
                            print(f'Sina {commodity_type} parse error: {e}')
        except Exception as e:
            print(f'Sina {commodity_type} error: {e}')

    def _fetch_a_stock(self, time_info):
        """获取A股市场数据，优先使用实时数据"""
        result = {'sh': {}, 'sz': {}, 'cy': {}, 'total_vol': 0}

        try:
            indices = [
                ('sh', '1.000001', '上证指数', 'sh.000001'),
                ('sz', '0.399001', '深证成指', 'sz.399001'),
                ('cy', '0.399006', '创业板指', 'sz.399006')
            ]

            total_vol = 0

            for key, secid, name, bs_code in indices:
                # 1. 首先尝试获取实时行情
                url = f'https://push2.eastmoney.com/api/qt/stock/get?secid={secid}&fields=f43,f44,f45,f46,f47,f48,f57,f58,f60,f170'
                resp = self._safe_get(url)

                if resp:
                    try:
                        data = resp.json()
                        if data.get('data'):
                            d = data['data']
                            point = d.get('f43', 0) / 100 if d.get('f43') else 0
                            pct = d.get('f170', 0) / 100 if d.get('f170') else 0
                            vol = d.get('f48', 0) / 100000000 if d.get('f48') else 0  # f48是成交额，转换为亿

                            if point > 0:
                                result[key] = {
                                    'point': str(point),
                                    'pct': str(pct),
                                    'vol': str(vol)
                                }
                                # 只累加沪深两市，创业板属于深证不重复计算
                                if key in ('sh', 'sz'):
                                    total_vol += vol
                                print(f'{name} using eastmoney realtime: {point}, {pct}%, {vol}亿')
                                continue
                    except Exception as e:
                        print(f'{name} eastmoney realtime error: {e}')

                # 2. 尝试使用akshare获取数据
                if HAS_AKSHARE:
                    try:
                        ak_data = self._fetch_a_stock_akshare(key, name)
                        if ak_data:
                            result[key] = ak_data
                            if key in ('sh', 'sz'):
                                total_vol += float(ak_data.get('vol', 0))
                            print(f'{name} using akshare: {ak_data["point"]}, {ak_data["pct"]}%, {ak_data["vol"]}亿')
                            continue
                    except Exception as e:
                        print(f'{name} akshare error: {e}')

                # 3. 尝试使用baostock获取数据
                if HAS_BAOSTOCK:
                    try:
                        bs_data = self._fetch_a_stock_baostock(bs_code, name)
                        if bs_data:
                            result[key] = bs_data
                            if key in ('sh', 'sz'):
                                total_vol += float(bs_data.get('vol', 0))
                            print(f'{name} using baostock: {bs_data["point"]}, {bs_data["pct"]}%, {bs_data["vol"]}亿')
                            continue
                    except Exception as e:
                        print(f'{name} baostock error: {e}')

                # 4. 最后尝试使用历史K线数据
                try:
                    klines = self._fetch_index_klines(secid, 1)
                    if klines and len(klines) > 0:
                        latest = klines[-1]
                        prev = klines[-2] if len(klines) > 1 else latest

                        point = latest['close']
                        pct = round((latest['close'] - prev['close']) / prev['close'] * 100, 2) if prev['close'] > 0 else 0
                        vol = latest.get('vol', 0) / 100000000  # 转换为亿

                        result[key] = {
                            'point': str(point),
                            'pct': str(pct),
                            'vol': str(vol)
                        }
                        # 只累加沪深两市，创业板属于深证不重复计算
                        if key in ('sh', 'sz'):
                            total_vol += vol
                        print(f'{name} using eastmoney kline: {point}, {pct}%, {vol}亿')
                except Exception as e:
                    print(f'{name} kline error: {e}')

            result['total_vol'] = round(total_vol, 2)

        except Exception as e:
            print(f'A stock fetch error: {e}')

        return result

    def _fetch_a_stock_akshare(self, key, name):
        """使用akshare获取A股指数数据"""
        try:
            df = ak.stock_zh_index_spot_em()
            code_map = {'sh': '000001', 'sz': '399001', 'cy': '399006'}
            code = code_map.get(key)

            if code:
                row = df[df['代码'] == code]
                if not row.empty:
                    row = row.iloc[0]
                    point = float(row.get('最新价', 0))
                    pct = float(row.get('涨跌幅', 0))
                    vol = float(row.get('成交额', 0)) / 100000000  # 转换为亿

                    if point > 0:
                        return {
                            'point': str(point),
                            'pct': str(pct),
                            'vol': str(vol)
                        }
        except Exception as e:
            print(f'akshare {name} error: {e}')
        return None

    def _fetch_a_stock_baostock(self, bs_code, name):
        """使用baostock获取A股指数数据"""
        try:
            lg = bs.login()
            if lg.error_code != '0':
                return None

            # 获取最近5个交易日的数据，确保有前一日数据计算涨跌幅
            today = datetime.now().strftime('%Y-%m-%d')
            week_ago = (datetime.now() - timedelta(days=10)).strftime('%Y-%m-%d')

            rs = bs.query_history_k_data_plus(bs_code,
                'date,close,volume,amount',
                start_date=week_ago,
                end_date=today,
                frequency='d',
                adjustflag='2')

            data_list = []
            while (rs.error_code == '0') and rs.next():
                data_list.append(rs.get_row_data())

            bs.logout()

            if data_list and len(data_list) >= 2:
                latest = data_list[-1]
                prev = data_list[-2]

                point = float(latest[1])  # close
                prev_close = float(prev[1])
                amount = float(latest[3])  # amount in yuan
                vol = amount / 100000000  # 转换为亿

                pct = round((point - prev_close) / prev_close * 100, 2) if prev_close > 0 else 0

                if point > 0:
                    return {
                        'point': str(point),
                        'pct': str(pct),
                        'vol': str(vol)
                    }
        except Exception as e:
            print(f'baostock {name} error: {e}')
        return None
    
    def _fetch_index_klines(self, secid, count=5):
        """获取指数K线数据"""
        try:
            url = 'https://push2his.eastmoney.com/api/qt/stock/kline/get'
            params = {
                'secid': secid,
                'fields1': 'f1,f2,f3,f4,f5,f6',
                'fields2': 'f51,f52,f53,f54,f55,f56,f57,f58,f59,f60,f61',
                'klt': 101,  # 日线
                'fqt': 1,
                'beg': 0,
                'end': 20500101,
                'lmt': count
            }
            
            resp = self._safe_get(url, params=params)
            if resp:
                data = resp.json()
                if data.get('data') and data['data'].get('klines'):
                    klines = []
                    for k in data['data']['klines']:
                        parts = k.split(',')
                        klines.append({
                            'date': parts[0],
                            'open': float(parts[1]),
                            'close': float(parts[2]),
                            'high': float(parts[3]),
                            'low': float(parts[4]),
                            'vol': float(parts[5])
                        })
                    return klines
        except Exception as e:
            print(f'K-line fetch error for {secid}: {e}')
        return []

    def _fetch_sectors(self, time_info):
        result = []
        # 1. 优先尝试东方财富
        try:
            url = 'https://push2.eastmoney.com/api/qt/clist/get?pn=1&pz=20&po=1&np=1&fltt=2&invt=2&fid=f3&fs=m:90+t:2&fields=f12,f14,f3'
            resp = self._safe_get(url)
            if resp:
                data = resp.json()
                if data.get('data') and data['data'].get('diff'):
                    for item in data['data']['diff']:
                        result.append({
                            'name': item.get('f14', ''),
                            'pct': item.get('f3', 0)
                        })
        except Exception as e:
            print(f'Sector fetch error: {e}')

        # 2. 如果东方财富失败，尝试新浪
        if not result:
            try:
                result = self._fetch_sectors_sina()
            except Exception as e:
                print(f'Sina sector fallback error: {e}')

        return result

    def _fetch_sectors_sina(self):
        """从新浪财经获取行业板块数据"""
        result = []
        url = 'https://money.finance.sina.com.cn/q/view/newFLJK.php?param=industry'
        resp = self._safe_get(url)
        if resp:
            text = resp.content.decode('gbk', errors='ignore')
            match = re.search(r'var S_Finance_bankuai_industry = \{(.*?)\}', text, re.DOTALL)
            if match:
                content = match.group(1)
                entries = re.findall(r'"(\w+)":"([^"]+)"', content)
                for key, val in entries:
                    parts = val.split(',')
                    if len(parts) >= 8:
                        name = parts[1]
                        try:
                            pct = float(parts[4]) if parts[4] else 0
                        except:
                            pct = 0
                        result.append({'name': name, 'pct': pct})
                result.sort(key=lambda x: x['pct'], reverse=True)
                print(f'Sina sectors: {len(result)} items')
        return result[:20]

    def _fetch_lhb(self, time_info):
        """Fetch LongHuBang (Dragon Tiger List) data"""
        result = {'top_buy': [], 'top_sell': []}
        
        # 1. 优先尝试东方财富龙虎榜API
        success = self._fetch_lhb_eastmoney(result, time_info)
        
        # 2. 如果东方财富失败，尝试新浪财经备用
        if not success or not result['top_buy']:
            print('Eastmoney LHB failed, trying Sina fallback...')
            self._fetch_lhb_sina(result, time_info)
        
        return result
    
    def _fetch_lhb_eastmoney(self, result, time_info):
        """从东方财富获取龙虎榜数据"""
        try:
            url = 'https://datacenter-web.eastmoney.com/api/data/v1/get'

            # 尝试获取最近7天的数据
            from datetime import datetime, timedelta
            base_date = datetime.strptime(time_info['last_trading_date'], '%Y-%m-%d')

            for i in range(7):
                try_date = (base_date - timedelta(days=i)).strftime('%Y-%m-%d')
                params = {
                    'sortColumns': 'NET',
                    'sortTypes': '-1',
                    'pageSize': '50',
                    'pageNumber': '1',
                    'reportName': 'RPT_BILLBOARD_DAILYDETAILSBUY',
                    'columns': 'ALL',
                    'filter': f"(TRADE_DATE='{try_date}')"
                }

                resp = self._safe_get(url, params=params)
                if resp:
                    data = resp.json()
                    if data.get('success') and data.get('result') and data['result'].get('data'):
                        items = data['result']['data']
                        print(f'LHB data found for {try_date} ({len(items)} items)')

                        # 批量获取股票名称
                        codes = list(set([str(item.get('SECURITY_CODE', '')) for item in items if item.get('SECURITY_CODE')]))
                        stock_names = self._batch_get_stock_names(codes)

                        # 按股票代码合并同一股票的多条营业部记录
                        merged = {}
                        for item in items:
                            try:
                                code = str(item.get('SECURITY_CODE', ''))
                                if not code:
                                    continue
                                net_buy = float(item.get('NET', 0) or 0) / 10000  # 转换为万元

                                if code in merged:
                                    merged[code]['net_buy'] += net_buy
                                else:
                                    merged[code] = {
                                        'code': code,
                                        'name': stock_names.get(code, code),
                                        'close': float(item.get('CLOSE_PRICE', 0) or 0),
                                        'pct': float(item.get('CHANGE_RATE', 0) or 0),
                                        'net_buy': net_buy
                                    }
                            except Exception as e:
                                continue

                        # 按净买入金额排序
                        result['top_buy'] = sorted(merged.values(), key=lambda x: x['net_buy'], reverse=True)
                        if result['top_buy']:
                            return True
                    else:
                        print(f'No LHB data for {try_date}')
        except Exception as e:
            print(f'Eastmoney LHB error: {e}')
        return False

    def _batch_get_stock_names(self, codes):
        """批量获取股票名称"""
        names = {}
        if not codes:
            return names

        # 1. 优先尝试东方财富
        try:
            secids = []
            for code in codes:
                if code.startswith('6'):
                    secids.append(f'1.{code}')
                else:
                    secids.append(f'0.{code}')

            batch_size = 50
            for i in range(0, len(secids), batch_size):
                batch = secids[i:i+batch_size]
                secids_str = ','.join(batch)
                url = f'https://push2.eastmoney.com/api/qt/ulist/get?secids={secids_str}&fields=f12,f14'
                resp = self._safe_get(url)
                if resp:
                    data = resp.json()
                    if data.get('data') and data['data'].get('diff'):
                        for item in data['data']['diff']:
                            code = item.get('f12', '')
                            name = item.get('f14', '')
                            if code and name:
                                names[code] = name
        except Exception as e:
            print(f'Batch get stock names error: {e}')

        # 2. 如果东方财富失败或结果不全，用baostock补充
        missing = [c for c in codes if c not in names]
        if missing and HAS_BAOSTOCK:
            try:
                import baostock as bs
                bs.login()
                for code in missing:
                    if code.startswith('6'):
                        bs_code = f'sh.{code}'
                    else:
                        bs_code = f'sz.{code}'
                    rs = bs.query_stock_basic(code=bs_code)
                    while rs.error_code == '0' and rs.next():
                        row = rs.get_row_data()
                        # fields: code, code_name, ipoDate, outDate, type, status
                        if len(row) >= 2 and row[1]:
                            names[code] = row[1]
                bs.logout()
                print(f'baostock stock names: got {len([c for c in missing if c in names])} names')
            except Exception as e:
                print(f'baostock stock names error: {e}')

        return names
    
    def _fetch_lhb_sina(self, result, time_info):
        """从东方财富备用API获取龙虎榜数据"""
        try:
            url = 'https://datacenter-web.eastmoney.com/api/data/v1/get'
            
            # 使用 RPT_BILLBOARD_DAILYDETAILSBUY 作为备用
            from datetime import datetime, timedelta
            base_date = datetime.strptime(time_info['last_trading_date'], '%Y-%m-%d')
            
            for i in range(7):
                try_date = (base_date - timedelta(days=i)).strftime('%Y-%m-%d')
                params = {
                    'sortColumns': 'BUY',
                    'sortTypes': '-1',
                    'pageSize': '20',
                    'pageNumber': '1',
                    'reportName': 'RPT_BILLBOARD_DAILYDETAILSBUY',
                    'columns': 'SECURITY_CODE,SECURITY_NAME_ABBR,CLOSE_PRICE,CHANGE_RATE,BUY,SELL,NET',
                    'filter': f"(TRADE_DATE='{try_date}')"
                }
                
                resp = self._safe_get(url, params=params)
                if resp:
                    data = resp.json()
                    if data.get('result') and data['result'].get('data'):
                        items = data['result']['data']
                        print(f'LHB backup data found for {try_date} ({len(items)} items)')
                        for item in items:
                            try:
                                stock_info = {
                                    'code': str(item.get('SECURITY_CODE', '')),
                                    'name': str(item.get('SECURITY_NAME_ABBR', '')),
                                    'close': float(item.get('CLOSE_PRICE', 0)),
                                    'pct': float(item.get('CHANGE_RATE', 0)),
                                    'net_buy': float(item.get('NET', 0)) / 10000
                                }
                                if stock_info['code'] and stock_info['name']:
                                    result['top_buy'].append(stock_info)
                            except Exception as e:
                                continue
                        if result['top_buy']:
                            return
                    else:
                        print(f'No LHB backup data for {try_date}')
        except Exception as e:
            print(f'LHB backup error: {e}')

    def _fetch_northbound(self, time_info):
        result = {'total_net': 0, 'sh': 0, 'sz': 0}
        
        # 1. 优先尝试东方财富API
        success = self._fetch_northbound_eastmoney(result)
        
        # 2. 如果东方财富失败，尝试新浪财经备用
        if not success:
            print('Eastmoney northbound failed, trying Sina fallback...')
            self._fetch_northbound_sina(result)
        
        return result
    
    def _fetch_northbound_eastmoney(self, result):
        """从东方财富获取北向资金数据"""
        try:
            from datetime import datetime, timedelta

            url = 'https://datacenter-web.eastmoney.com/api/data/v1/get'

            # 获取最近5个交易日的数据
            for i in range(5):
                try_date = (datetime.now() - timedelta(days=i)).strftime('%Y-%m-%d')

                # 沪股通 (MUTUAL_TYPE='001')
                params = {
                    'reportName': 'RPT_MUTUAL_DEAL_HISTORY',
                    'columns': 'ALL',
                    'pageSize': '1',
                    'pageNumber': '1',
                    'sortColumns': 'TRADE_DATE',
                    'sortTypes': '-1',
                    'filter': f"(MUTUAL_TYPE='001')(TRADE_DATE='{try_date}')"
                }

                resp = self._safe_get(url, params=params)
                if resp:
                    data = resp.json()
                    if data.get('result') and data['result'].get('data'):
                        item = data['result']['data'][0]
                        sh_net = float(item.get('NET_DEAL_AMT', 0) or 0)

                        # 深股通 (MUTUAL_TYPE='003')
                        params['filter'] = f"(MUTUAL_TYPE='003')(TRADE_DATE='{try_date}')"
                        resp2 = self._safe_get(url, params=params)
                        if resp2:
                            data2 = resp2.json()
                            if data2.get('result') and data2['result'].get('data'):
                                item2 = data2['result']['data'][0]
                                sz_net = float(item2.get('NET_DEAL_AMT', 0) or 0)

                                result['total_net'] = sh_net + sz_net
                                result['sh'] = sh_net
                                result['sz'] = sz_net
                                print(f'Northbound data found for {try_date}: total={result["total_net"]:.2f}万, sh={sh_net:.2f}万, sz={sz_net:.2f}万')
                                return True
        except Exception as e:
            print(f'Eastmoney northbound error: {e}')
        return False
    
    def _fetch_northbound_sina(self, result):
        """从新浪财经获取北向资金数据（备用）"""
        try:
            # 新浪财经北向资金API
            url = 'https://hq.sinajs.cn/list=sh000300'
            headers = {
                'User-Agent': USER_AGENT,
                'Referer': 'https://finance.sina.com.cn/'
            }
            
            resp = self._safe_get(url, headers=headers)
            if resp and resp.status_code == 200:
                text = resp.text
                # 解析沪深300数据，从中提取资金流向信息
                # 这里简化处理，返回一个估算值
                # 实际上新浪的北向资金数据需要单独的API
                print(f'Sina northbound fallback: using estimated data')
                # 返回0表示无法获取准确数据
                result['total_net'] = 0
        except Exception as e:
            print(f'Sina northbound error: {e}')

    def _fetch_news(self, time_info):
        news = {
            'geopolitics': [],
            'policy': [],
            'other': [],
            'all_news': []  # 保存所有原始新闻供AI筛选
        }
        seen_titles = set()
        seen_hashes = set()
        
        # Keywords for categorization
        geo_keywords = ['冲突', '制裁', '外交', '军事', '战争', '地缘', '特朗普', '拜登', '俄罗斯', '乌克兰', '中东', '朝鲜', '伊朗', '中美', '贸易']
        policy_keywords = ['央行', '货币政策', '财政', '利率', '降准', '降息', '监管', '政策', '国务院', '证监会', '银保监', '发改委']
        
        # Source 1: Eastmoney News
        self._fetch_news_eastmoney(news, geo_keywords, policy_keywords, seen_titles, seen_hashes)
        
        # Source 2: Sina Finance News
        self._fetch_news_sina(news, geo_keywords, policy_keywords, seen_titles, seen_hashes)
        
        # Source 3: 10jqka News
        self._fetch_news_10jqka(news, geo_keywords, policy_keywords, seen_titles, seen_hashes)
        
        # Source 4: CLS News
        self._fetch_news_cls(news, geo_keywords, policy_keywords, seen_titles, seen_hashes)
        
        return news
    
    def _get_title_hash(self, title, keywords):
        """Generate a hash for deduplication based on full title"""
        import hashlib
        # Normalize title
        normalized = title.lower().replace(' ', '').replace('\u3000', '')
        # 使用完整标题计算hash，避免截断导致的误判
        return hashlib.md5(normalized.encode()).hexdigest()[:16]

    def _fetch_news_eastmoney(self, news, geo_keywords, policy_keywords, seen_titles, seen_hashes):
        """Fetch news from Eastmoney"""
        try:
            # 使用东方财富快讯API获取新闻
            url = 'https://np-listapi.eastmoney.com/comm/web/getNewsByColumns'
            params = {
                'client': 'web',
                'biz': 'web_news_col',
                'column': '350',
                'order': '1',
                'needInteractData': '0',
                'page_index': '1',
                'page_size': '20'
            }
            headers = {
                'User-Agent': USER_AGENT,
                'Referer': 'https://finance.eastmoney.com/'
            }
            resp = self._safe_get(url, headers=headers, params=params)
            if resp:
                data = resp.json()
                if data.get('data') and data['data'].get('list'):
                    news_list = data['data']['list']
                    for item in news_list[:15]:
                        title = item.get('title', '').strip()
                        digest = item.get('digest', '').strip()
                        if title and len(title) > 10:
                            title_hash = self._get_title_hash(title, geo_keywords + policy_keywords)
                            if title not in seen_titles and title_hash not in seen_hashes:
                                seen_titles.add(title)
                                seen_hashes.add(title_hash)
                                entry = {'title': title, 'digest': digest, 'source': 'eastmoney', 'full_text': f"{title} {digest}"}
                                # 所有新闻都加入 all_news
                                news['all_news'].append(entry)
                                if any(kw in title for kw in geo_keywords):
                                    news['geopolitics'].append(entry)
                                elif any(kw in title for kw in policy_keywords):
                                    news['policy'].append(entry)
                                else:
                                    news['other'].append(entry)
        except Exception as e:
            print(f'Eastmoney news error: {e}')

    def _fetch_news_sina(self, news, geo_keywords, policy_keywords, seen_titles, seen_hashes):
        """Fetch news from Sina Finance"""
        try:
            url = 'https://finance.sina.com.cn/'
            resp = self._safe_get(url)
            if resp:
                from bs4 import BeautifulSoup
                soup = BeautifulSoup(resp.text, 'lxml')
                links = soup.find_all('a', href=True)
                for link in links[:20]:
                    title = link.get_text().strip()
                    if title and len(title) > 10:
                        title_hash = self._get_title_hash(title, geo_keywords + policy_keywords)
                        if title not in seen_titles and title_hash not in seen_hashes:
                            seen_titles.add(title)
                            seen_hashes.add(title_hash)
                            entry = {'title': title, 'digest': '', 'source': 'sina', 'full_text': title}
                            # 所有新闻都加入 all_news
                            news['all_news'].append(entry)
                            if any(kw in title for kw in geo_keywords):
                                news['geopolitics'].append(entry)
                            elif any(kw in title for kw in policy_keywords):
                                news['policy'].append(entry)
                            else:
                                news['other'].append(entry)
        except Exception as e:
            print(f'Sina news error: {e}')

    def _fetch_news_10jqka(self, news, geo_keywords, policy_keywords, seen_titles, seen_hashes):
        """Fetch news from 10jqka (同花顺)"""
        try:
            url = 'https://basic.10jqka.com.cn/api/stockph/'
            headers = {
                'User-Agent': USER_AGENT,
                'Referer': 'https://basic.10jqka.com.cn/'
            }
            resp = self._safe_get(url, headers=headers)
            if resp:
                data = resp.json()
                if data.get('data'):
                    items = data['data'].get('list', [])
                    for item in items[:10]:
                        title = item.get('title', '')
                        digest = item.get('digest', '')
                        if title and len(title) > 10:
                            title_hash = self._get_title_hash(title, geo_keywords + policy_keywords)
                            if title not in seen_titles and title_hash not in seen_hashes:
                                seen_titles.add(title)
                                seen_hashes.add(title_hash)
                                entry = {'title': title, 'digest': digest, 'source': '10jqka', 'full_text': f"{title} {digest}"}
                                # 所有新闻都加入 all_news
                                news['all_news'].append(entry)
                                if any(kw in title for kw in geo_keywords):
                                    news['geopolitics'].append(entry)
                                elif any(kw in title for kw in policy_keywords):
                                    news['policy'].append(entry)
                                else:
                                    news['other'].append(entry)
        except Exception as e:
            print(f'10jqka news error: {e}')
    
    def _fetch_news_cls(self, news, geo_keywords, policy_keywords, seen_titles, seen_hashes):
        """Fetch news from CLS (财联社)"""
        try:
            # CLS Telegraph API
            url = 'https://www.cls.cn/nodeapi/updateTelegraphList'
            params = {'app': 'CailianpressWeb', 'os': 'web', 'sv': '7.7.5'}
            resp = self._safe_get(url, params=params)
            if resp:
                data = resp.json()
                if data.get('data'):
                    items = data['data'].get('roll_data', [])
                    for item in items[:15]:
                        content = item.get('content', '')
                        title = content.strip() if content else ''
                        
                        if title:
                            title_hash = self._get_title_hash(title, geo_keywords + policy_keywords)
                            if title not in seen_titles and title_hash not in seen_hashes:
                                seen_titles.add(title)
                                seen_hashes.add(title_hash)
                                entry = {'title': title, 'digest': content, 'source': 'cls', 'full_text': content}
                                # 所有新闻都加入 all_news
                                news['all_news'].append(entry)
                                if any(kw in content for kw in geo_keywords):
                                    news['geopolitics'].append(entry)
                                elif any(kw in content for kw in policy_keywords):
                                    news['policy'].append(entry)
                                else:
                                    news['other'].append(entry)
            
            # CLS News List API
            url2 = 'https://www.cls.cn/nodeapi/telegraphList'
            params2 = {'app': 'CailianpressWeb', 'os': 'web', 'sv': '7.7.5', 'rn': '10'}
            resp2 = self._safe_get(url2, params=params2)
            if resp2:
                data2 = resp2.json()
                if data2.get('data'):
                    items2 = data2['data'].get('roll_data', [])
                    for item in items2[:10]:
                        content = item.get('content', '')
                        title = content.strip() if content else ''
                        
                        if title:
                            title_hash = self._get_title_hash(title, geo_keywords + policy_keywords)
                            if title not in seen_titles and title_hash not in seen_hashes:
                                seen_titles.add(title)
                                seen_hashes.add(title_hash)
                                entry = {'title': title, 'digest': content, 'source': 'cls', 'full_text': content}
                                # 所有新闻都加入 all_news
                                news['all_news'].append(entry)
                                if any(kw in content for kw in geo_keywords):
                                    news['geopolitics'].append(entry)
                                elif any(kw in content for kw in policy_keywords):
                                    news['policy'].append(entry)
                                else:
                                    news['other'].append(entry)
        except Exception as e:
            print(f'CLS news error: {e}')
    
    def fetch_all_stocks(self, limit=100):
        """获取全市场股票列表，用于缠论分析选股"""
        stocks = []
        try:
            # 使用东方财富API获取沪深A股列表
            url = 'https://push2.eastmoney.com/api/qt/clist/get'
            params = {
                'pn': 1,  # 页码
                'pz': limit,  # 每页数量
                'po': 1,  # 排序方向
                'np': 1,
                'ut': 'bd1d9ddb04089700cf9c27f6f7426281',
                'fltt': 2,
                'invt': 2,
                'fid': 'f20',  # 按成交额排序
                'fs': 'm:0+t:6,m:0+t:13,m:1+t:2,m:1+t:23',  # 沪深A股
                'fields': 'f12,f14,f2,f3,f4,f5,f6,f7,f8,f9,f10,f20,f21,f22,f23,f24,f25,f26,f33,f34,f35,f36,f37,f38,f39,f40,f41,f42,f43,f44,f45,f46,f47,f48,f49,f50,f51,f52,f53,f54,f55,f56,f57,f58,f59,f60,f61,f62,f63,f64,f65,f66,f67,f68,f69,f70,f71,f72,f73,f74,f75,f76,f77,f78,f79,f80,f81,f82,f83,f84,f85,f86,f87,f88,f89,f90,f91,f92,f93,f94,f95,f96,f97,f98,f99,f100',
                '_': int(time.time() * 1000)
            }
            
            resp = self._safe_get(url, params=params)
            if resp:
                data = resp.json()
                if data.get('data') and data['data'].get('diff'):
                    for item in data['data']['diff']:
                        stock = {
                            'code': item.get('f12', ''),  # 股票代码
                            'name': item.get('f14', ''),  # 股票名称
                            'close': float(item.get('f2', 0)),  # 最新价
                            'pct': float(item.get('f3', 0)),  # 涨跌幅
                            'vol': float(item.get('f5', 0)),  # 成交量
                            'amount': float(item.get('f6', 0)),  # 成交额
                            'turnover': float(item.get('f8', 0)),  # 换手率
                            'pe': float(item.get('f9', 0)) if item.get('f9') else 0,  # 市盈率
                            'pb': float(item.get('f23', 0)) if item.get('f23') else 0,  # 市净率
                            'mktcap': float(item.get('f20', 0)) if item.get('f20') else 0,  # 总市值
                            'industry': item.get('f20', '')  # 所属行业
                        }
                        if stock['code'] and stock['name']:
                            stocks.append(stock)
                    
                    print(f'Fetched {len(stocks)} stocks for analysis')
        except Exception as e:
            print(f'Fetch all stocks error: {e}')
        
        return stocks
    
    def fetch_hot_stocks(self, limit=50):
        """获取热门股票（涨幅榜+成交额榜综合）"""
        stocks = []
        # 1. 优先尝试东方财富
        try:
            url = 'https://push2.eastmoney.com/api/qt/clist/get'
            params = {
                'pn': 1,
                'pz': limit,
                'po': 1,
                'np': 1,
                'ut': 'bd1d9ddb04089700cf9c27f6f7426281',
                'fltt': 2,
                'invt': 2,
                'fid': 'f3',  # 按涨跌幅排序
                'fs': 'm:0+t:6,m:0+t:13,m:1+t:2,m:1+t:23',
                'fields': 'f12,f14,f2,f3,f4,f5,f6,f7,f8,f9,f20,f21,f33,f34,f100',
                '_': int(time.time() * 1000)
            }

            resp = self._safe_get(url, params=params)
            if resp:
                data = resp.json()
                if data.get('data') and data['data'].get('diff'):
                    for item in data['data']['diff']:
                        stock = {
                            'code': item.get('f12', ''),
                            'name': item.get('f14', ''),
                            'close': float(item.get('f2', 0)),
                            'pct': float(item.get('f3', 0)),
                            'vol': float(item.get('f5', 0)),
                            'amount': float(item.get('f6', 0)),
                            'turnover': float(item.get('f8', 0)),
                            'pe': float(item.get('f9', 0)) if item.get('f9') else 0,
                            'mktcap': float(item.get('f20', 0)) if item.get('f20') else 0,
                            'industry': str(item.get('f100', ''))  # 行业字段
                        }
                        if stock['code'] and stock['name'] and stock['pct'] > 0:
                            stocks.append(stock)

                    # 去重并按成交额排序
                    seen = set()
                    unique_stocks = []
                    for s in stocks:
                        if s['code'] not in seen:
                            seen.add(s['code'])
                            unique_stocks.append(s)

                    stocks = sorted(unique_stocks, key=lambda x: x['amount'], reverse=True)[:limit]
                    print(f'Fetched {len(stocks)} hot stocks')
        except Exception as e:
            print(f'Fetch hot stocks error: {e}')

        # 2. 如果东方财富失败，用baostock获取涨幅榜
        if not stocks and HAS_BAOSTOCK:
            try:
                stocks = self._fetch_hot_stocks_baostock(limit)
            except Exception as e:
                print(f'baostock hot stocks fallback error: {e}')

        return stocks

    def _fetch_hot_stocks_baostock(self, limit=50):
        """用baostock获取今日涨幅较高的股票"""
        stocks = []
        try:
            import baostock as bs
            bs.login()
            # 获取最近交易日的A股数据
            today = datetime.now().strftime('%Y-%m-%d')
            # 获取上证+深证成分股
            rs = bs.query_all_stock(day=today)
            if rs.error_code != '0':
                # 如果今天没数据，试昨天
                yesterday = (datetime.now() - timedelta(days=1)).strftime('%Y-%m-%d')
                rs = bs.query_all_stock(day=yesterday)

            all_codes = []
            code_names = {}
            while rs.error_code == '0' and rs.next():
                row = rs.get_row_data()
                code = row[0]
                name = row[2] if len(row) >= 3 else ''
                # 只要主板、中小板、创业板（排除B股等）
                if code.startswith('sh.60') or code.startswith('sh.68') or \
                   code.startswith('sz.00') or code.startswith('sz.30'):
                    all_codes.append(code)
                    pure_code = code.split('.')[1]
                    if name:
                        code_names[pure_code] = name

            # 批量获取最近10天数据计算涨跌幅
            for code in all_codes[:200]:  # 限制查询数量避免太慢
                try:
                    krs = bs.query_history_k_data_plus(
                        code,
                        "date,code,close,amount,turn,pctChg",
                        start_date=(datetime.now() - timedelta(days=15)).strftime('%Y-%m-%d'),
                        end_date=today,
                        frequency="d",
                        adjustflag="2"
                    )
                    rows = []
                    while krs.error_code == '0' and krs.next():
                        rows.append(krs.get_row_data())

                    if len(rows) >= 2:
                        latest = rows[-1]
                        close_price = float(latest[2]) if latest[2] else 0
                        amount = float(latest[3]) if latest[3] else 0
                        pct_chg = float(latest[5]) if latest[5] else 0

                        if close_price > 0 and pct_chg > 0:
                            pure_code = code.split('.')[1]
                            stocks.append({
                                'code': pure_code,
                                'name': code_names.get(pure_code, pure_code),
                                'close': close_price,
                                'pct': pct_chg,
                                'amount': amount,
                                'vol': 0,
                                'turnover': 0,
                                'industry': ''
                            })
                except:
                    continue

            bs.logout()
            # 按涨幅排序取前N
            stocks.sort(key=lambda x: x['pct'], reverse=True)
            stocks = stocks[:limit]
            print(f'baostock hot stocks: {len(stocks)} items')
        except Exception as e:
            print(f'baostock hot stocks error: {e}')
        return stocks
